# ============================================================
# Lecture 15 -- Community Ecology Models
# Ecological Modelling with R, Python, and Julia
#
# Dataset:
#   data/dune_species.csv (+ data/dune_env.csv for the JSDM covariate)
#     Jongman, ter Braak & van Tongeren -- Dutch dune meadow vegetation
#     survey, 20 sites x 30 species
#
# Lecture 4 asked whether GROUPS differ in composition (PERMANOVA/NMDS).
# Today we ask how SPECIES relate to EACH OTHER: co-occurrence, null
# models, networks, and a simplified joint species distribution model.
#
# Methods:
#   1. Pairwise Spearman correlation among species across sites
#   2. Null-model co-occurrence test (C-score) -- vegan::oecosimu()
#      Reference: Gotelli, N.J. (2000) "Null model analysis of species
#      co-occurrence patterns." Ecology 81(9): 2606-2621.
#   3. Species co-occurrence network -- igraph
#   4. Simplified JSDM: per-species GLM + residual correlation matrix
#
# Assumes working directory = repository root, i.e. run as:
#   Rscript code/R/lecture_15_community_models.R
# ============================================================

suppressMessages(library(vegan))
suppressMessages(library(igraph))

dir.create("figures", showWarnings = FALSE)

cat("=== Lecture 15: Community Ecology Models (R) ===\n\n")

## ------------------------------------------------------------
## 0. Load data
## ------------------------------------------------------------

dune <- read.csv("data/dune_species.csv", stringsAsFactors = FALSE)
site_ids <- as.character(dune$site)
comm <- as.matrix(dune[, setdiff(names(dune), "site")])
rownames(comm) <- site_ids
storage.mode(comm) <- "numeric"

sp_names <- colnames(comm)
n_sp <- ncol(comm)
n_site <- nrow(comm)
cat(sprintf("Community matrix: %d sites x %d species\n\n", n_site, n_sp))

## ------------------------------------------------------------
## 1. Pairwise Spearman correlation among species across sites
##    Each species' abundance vector (length = 20 sites) is correlated
##    against every other species' vector. This is a purely descriptive,
##    raw-data association -- it does NOT yet account for the fact that
##    species which are individually common will co-occur more often by
##    chance alone. Step 2 fixes that.
## ------------------------------------------------------------

cor_mat <- matrix(NA_real_, n_sp, n_sp, dimnames = list(sp_names, sp_names))
p_mat   <- matrix(NA_real_, n_sp, n_sp, dimnames = list(sp_names, sp_names))

for (i in 1:(n_sp - 1)) {
  for (j in (i + 1):n_sp) {
    xi <- comm[, i]; xj <- comm[, j]
    if (sd(xi) > 0 && sd(xj) > 0) {
      ct <- suppressWarnings(cor.test(xi, xj, method = "spearman"))
      cor_mat[i, j] <- cor_mat[j, i] <- unname(ct$estimate)
      p_mat[i, j]   <- p_mat[j, i]   <- ct$p.value
    }
  }
}
diag(cor_mat) <- 1
diag(p_mat) <- 0

## Significant positive pairs at uncorrected p < 0.05.
## CAVEAT: with 30 species there are choose(30,2) = 435 tests -- at
## p < 0.05 uncorrected we expect ~22 false positives by chance alone.
## This is fine for a teaching example but a real analysis should use
## FDR correction (p.adjust(method = "fdr")) or, better, rely on the
## null-model test in Step 2, which is built for exactly this problem.
n_pairs <- choose(n_sp, 2)
sig_pos <- (p_mat < 0.05) & (cor_mat > 0)
diag(sig_pos) <- FALSE
n_sig <- sum(sig_pos) / 2

cat("--- Pairwise Spearman correlations among species ---\n")
cat(sprintf("Total species pairs tested: %d\n", n_pairs))
cat(sprintf("Significant positive pairs (uncorrected p < 0.05): %d (%.1f%%)\n",
            n_sig, 100 * n_sig / n_pairs))
cat(sprintf("Expected false positives under the null at alpha=0.05: ~%.1f\n\n",
            0.05 * n_pairs))

## ------------------------------------------------------------
## 2. Null-model co-occurrence test -- the C-score
##    Gotelli (2000, Ecology) formalized null-model testing of species
##    co-occurrence: compare the OBSERVED checkerboard (C-)score of a
##    presence-absence matrix to a null distribution generated by
##    randomizing the matrix while preserving row and column sums (the
##    "fixed-fixed" algorithm; vegan calls it "quasiswap"). A C-score
##    higher than the null range implies competitive/segregated
##    structure; lower implies aggregation/facilitation.
## ------------------------------------------------------------

pa <- (comm > 0) * 1  # presence-absence

set.seed(42)
null_test <- oecosimu(pa, nestedchecker, method = "quasiswap", nsimul = 999)

cat("--- Null-model co-occurrence test (C-score, vegan::oecosimu) ---\n")
print(null_test)
cat("\n")

obs_cscore <- unname(null_test$statistic$statistic["checkerboards"])
z_score    <- unname(null_test$oecosimu$z["checkerboards"])
p_null     <- null_test$oecosimu$pval
cat(sprintf("Observed checkerboard units = %.1f, SES (z) = %.2f, p = %.3f\n",
            obs_cscore, z_score, p_null))
cat("Interpretation: SES > 0 with p < 0.05 => more checkerboard structure\n")
cat("(species segregation) than expected under random co-occurrence.\n\n")

## ------------------------------------------------------------
## 3. Species co-occurrence network -- igraph
##    Nodes = species; edges = significant POSITIVE pairwise association
##    (from Step 1). This turns the pairwise correlation table into a
##    visual, interpretable structure.
## ------------------------------------------------------------

adj <- sig_pos * 1
diag(adj) <- 0

g <- graph_from_adjacency_matrix(adj, mode = "undirected", diag = FALSE)
g <- delete_vertices(g, which(degree(g) == 0))  # drop isolated species for clarity

deg <- degree(g)
dens <- edge_density(g)
top3 <- sort(deg, decreasing = TRUE)[1:min(3, length(deg))]

cat("--- Co-occurrence network summary (igraph) ---\n")
cat(sprintf("Nodes (connected species): %d / %d total species\n",
            vcount(g), n_sp))
cat(sprintf("Edges (significant positive associations): %d\n", ecount(g)))
cat(sprintf("Network density: %.3f\n", dens))
cat(sprintf("Mean degree: %.2f\n", mean(deg)))
cat("Top-3 hub species (highest degree):\n")
print(top3)
cat("\n")

set.seed(42)
png("figures/lecture_15_cooccurrence_network.png", width = 1500, height = 1300, res = 150)
layout_xy <- layout_with_fr(g)
plot(g, layout = layout_xy,
     vertex.size = 6 + 2 * deg,
     vertex.label.cex = 0.65,
     vertex.label.color = "black",
     vertex.color = "#8E5AA8",
     vertex.frame.color = "white",
     edge.color = adjustcolor("#2E6E8E", alpha.f = 0.6),
     main = "Dune Meadow Species Co-occurrence Network\n(edges = significant positive Spearman association, p < 0.05)")
dev.off()
cat("Saved figures/lecture_15_cooccurrence_network.png\n\n")

## ------------------------------------------------------------
## 4. Simplified JSDM: per-species GLM + residual correlation
##    Fit each species' abundance against a shared environmental
##    covariate (A1 = soil organic matter horizon depth from dune_env.csv).
##    After removing the shared environmental response, whatever
##    correlation REMAINS among the Pearson residuals is the "biotic
##    signal" -- the part of co-occurrence not explained by shared habitat
##    preference. This is a hand-rolled stand-in for the residual
##    covariance structure that Hmsc / boral / gllvm estimate jointly and
##    more rigorously.
## ------------------------------------------------------------

dune_env <- read.csv("data/dune_env.csv", stringsAsFactors = FALSE)
stopifnot(identical(as.character(dune_env$site), site_ids))
A1 <- dune_env$A1

resid_mat <- matrix(NA_real_, n_site, n_sp, dimnames = list(site_ids, sp_names))
for (j in 1:n_sp) {
  y <- comm[, j]
  fit <- glm(y ~ A1, family = poisson())
  resid_mat[, j] <- residuals(fit, type = "pearson")
}

resid_cor <- cor(resid_mat, method = "spearman")
raw_cor   <- cor_mat

## Compare: how much does mean |correlation| shrink after accounting for A1?
lower_tri <- lower.tri(raw_cor)
mean_abs_raw   <- mean(abs(raw_cor[lower_tri]), na.rm = TRUE)
mean_abs_resid <- mean(abs(resid_cor[lower_tri]), na.rm = TRUE)

cat("--- Simplified JSDM: species-GLM residual correlation (vs A1) ---\n")
cat(sprintf("Mean |raw Spearman correlation| among species:      %.3f\n", mean_abs_raw))
cat(sprintf("Mean |residual correlation| after controlling for A1: %.3f\n", mean_abs_resid))
if (mean_abs_resid < mean_abs_raw) {
  cat("Residual correlation is SMALLER than raw: A1 (soil organic matter)\n")
  cat("explains part of the raw co-occurrence signal.\n")
} else {
  cat("Residual correlation is NOT smaller than raw here: A1 alone does not\n")
  cat("soak up much of the co-occurrence signal for this dataset -- either\n")
  cat("the true environmental driver is something else (e.g. Moisture), or\n")
  cat("a genuine biotic/unmeasured-covariate signal dominates.\n")
}
cat("Whatever correlation remains among residuals after accounting for the\n")
cat("shared environmental response is the candidate biotic-interaction\n")
cat("signal -- the core logic behind JSDMs (Hmsc/boral/gllvm).\n\n")

cat("=== Done ===\n")

# --- EXERCISES ---
# TODO 1: Rerun the co-occurrence analysis (Steps 1-3) on data/BCI_species.csv.
#         Subset to the ~30 most abundant species first (colSums, then
#         head(order(colSums, decreasing=TRUE), 30)) to keep runtime
#         reasonable. Compare network density to the dune network.
# TODO 2: Identify the top-3 hub species in the dune co-occurrence network
#         and look up (or reason about) their functional traits/life
#         history. What ecological mechanism could explain why they have
#         so many significant positive associations?
# TODO 3: Refit the simplified JSDM (Step 4) using Moisture instead of A1
#         as the environmental covariate. Does mean residual correlation
#         drop by more or less than with A1?
# TODO 4: Repeat the null-model C-score test (Step 2) using a different
#         null-model algorithm, e.g. method = "r1" or method = "swap" in
#         oecosimu(). Do the SES and p-value change much? What does that
#         tell you about the sensitivity of null-model results to the
#         choice of randomization algorithm?
