"""
Lecture 15: Community Ecology Models (Python)
Ecological Modelling with R, Python, and Julia

Dataset:
  data/dune_species.csv (+ data/dune_env.csv for the JSDM covariate)
    Jongman, ter Braak & van Tongeren -- Dutch dune meadow vegetation
    survey, 20 sites x 30 species

Lecture 4 asked whether GROUPS differ in composition (PERMANOVA/NMDS).
Today we ask how SPECIES relate to EACH OTHER: co-occurrence, null
models, networks, and a simplified joint species distribution model.

Methods:
  1. Pairwise Spearman correlation among species across sites
  2. Hand-rolled null-model co-occurrence test (C-score), because vegan's
     quasiswap null model has no direct Python equivalent installed here.
     Reference: Gotelli, N.J. (2000) "Null model analysis of species
     co-occurrence patterns." Ecology 81(9): 2606-2621.
  3. Species co-occurrence network -- networkx
  4. Simplified JSDM: per-species GLM (Poisson) + residual correlation

Convention used all semester:
  - Run scripts with the working directory set to the repository root.
  - Read inputs from   data/<file>.csv
  - Write figures to   figures/lecture_NN_<slug>.png
"""

import os

import matplotlib
matplotlib.use("Agg")  # headless-safe backend
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
from scipy.stats import spearmanr
import statsmodels.api as sm

os.makedirs("figures", exist_ok=True)
rng = np.random.default_rng(42)

print("=== Lecture 15: Community Ecology Models (Python) ===\n")

# ---- 0. Load data --------------------------------------------------------------
dune = pd.read_csv("data/dune_species.csv")
site_ids = dune["site"].astype(str).to_numpy()
comm = dune.drop(columns=["site"]).to_numpy(dtype=float)
sp_names = dune.drop(columns=["site"]).columns.to_numpy()
n_site, n_sp = comm.shape
print(f"Community matrix: {n_site} sites x {n_sp} species\n")

# ---- 1. Pairwise Spearman correlation among species ----------------------------
# Each species' abundance vector (length = 20 sites) is correlated against
# every other species' vector. This is a purely descriptive, raw-data
# association -- it does NOT yet account for the fact that species which are
# individually common will co-occur more often by chance alone. Step 2 fixes
# that.
cor_mat = np.eye(n_sp)
p_mat = np.zeros((n_sp, n_sp))
for i in range(n_sp - 1):
    for j in range(i + 1, n_sp):
        xi, xj = comm[:, i], comm[:, j]
        if xi.std() > 0 and xj.std() > 0:
            r, p = spearmanr(xi, xj)
        else:
            r, p = 0.0, 1.0
        cor_mat[i, j] = cor_mat[j, i] = r
        p_mat[i, j] = p_mat[j, i] = p

n_pairs = n_sp * (n_sp - 1) // 2
sig_pos = (p_mat < 0.05) & (cor_mat > 0)
np.fill_diagonal(sig_pos, False)
n_sig = sig_pos.sum() // 2

print("--- Pairwise Spearman correlations among species ---")
print(f"Total species pairs tested: {n_pairs}")
print(f"Significant positive pairs (uncorrected p < 0.05): {n_sig} "
      f"({100 * n_sig / n_pairs:.1f}%)")
print(f"Expected false positives under the null at alpha=0.05: ~{0.05 * n_pairs:.1f}\n")
print("CAVEAT: 30 species means 435 tests -- uncorrected p<0.05 gives ~22\n"
      "false positives by chance. Fine for teaching; a real analysis should\n"
      "use FDR correction or, better, the null-model test below.\n")

# ---- 2. Hand-rolled null-model co-occurrence test (C-score) --------------------
# Gotelli (2000, Ecology) formalized null-model testing of species
# co-occurrence: compare the OBSERVED checkerboard (C-)score of a
# presence-absence matrix to a null distribution generated by randomizing the
# matrix while preserving row and column sums (the "fixed-fixed" algorithm,
# equivalent to vegan's "quasiswap"). We implement this with a curveball /
# trial-swap algorithm: repeatedly pick two rows and two columns forming a
# checkerboard submatrix [[1,0],[0,1]] and swap it to [[0,1],[1,0]] (or vice
# versa) -- this preserves every row sum and column sum exactly.

pa = (comm > 0).astype(int)


def cscore(pa_mat):
    """Stone & Roberts (1990) C-score, averaged over all species pairs."""
    n = pa_mat.shape[1]
    row_totals = pa_mat.sum(axis=0)  # occurrences per species (column)
    total = 0.0
    count = 0
    for i in range(n - 1):
        for j in range(i + 1, n):
            shared = np.sum((pa_mat[:, i] == 1) & (pa_mat[:, j] == 1))
            ri, rj = row_totals[i], row_totals[j]
            total += (ri - shared) * (rj - shared)
            count += 1
    return total / count


def swap_null(pa_mat, n_swaps, rng):
    """One 'fixed-fixed' null replicate via checkerboard swaps.

    Preserves row sums (species occurrence totals) and column sums (site
    richness totals) exactly -- the standard co-occurrence null model.
    """
    m = pa_mat.copy()
    n_site_, n_sp_ = m.shape
    tries = 0
    swaps_done = 0
    max_tries = n_swaps * 50
    while swaps_done < n_swaps and tries < max_tries:
        tries += 1
        r1, r2 = rng.choice(n_site_, size=2, replace=False)
        c1, c2 = rng.choice(n_sp_, size=2, replace=False)
        block = m[np.ix_([r1, r2], [c1, c2])]
        if np.array_equal(block, [[1, 0], [0, 1]]):
            m[r1, c1], m[r1, c2] = 0, 1
            m[r2, c1], m[r2, c2] = 1, 0
            swaps_done += 1
        elif np.array_equal(block, [[0, 1], [1, 0]]):
            m[r1, c1], m[r1, c2] = 1, 0
            m[r2, c1], m[r2, c2] = 0, 1
            swaps_done += 1
    return m


obs_c = cscore(pa)
n_null = 999
null_c = np.empty(n_null)
mat = pa.copy()
for k in range(n_null):
    mat = swap_null(mat, n_swaps=200, rng=rng)  # burn in / re-randomize each draw
    null_c[k] = cscore(mat)

z_score = (obs_c - null_c.mean()) / null_c.std(ddof=1)
p_null = (np.sum(null_c >= obs_c) + 1) / (n_null + 1)  # one-sided: segregation

print("--- Null-model co-occurrence test (hand-rolled C-score, fixed-fixed swap) ---")
print(f"Observed C-score: {obs_c:.3f}")
print(f"Null mean C-score: {null_c.mean():.3f} (SD {null_c.std(ddof=1):.3f})")
print(f"SES (z) = {z_score:.2f}, p = {p_null:.3f} ({n_null} null replicates)")
print("Interpretation: SES > 0 with p < 0.05 => observed C-score higher than\n"
      "expected under random co-occurrence => species segregation (checkerboard\n"
      "structure), consistent with the R vegan::oecosimu result.\n")

# ---- 3. Species co-occurrence network -- networkx ------------------------------
# Nodes = species; edges = significant POSITIVE pairwise association (Step 1).

G = nx.Graph()
G.add_nodes_from(sp_names)
for i in range(n_sp - 1):
    for j in range(i + 1, n_sp):
        if sig_pos[i, j]:
            G.add_edge(sp_names[i], sp_names[j], weight=cor_mat[i, j])

isolated = list(nx.isolates(G))
G.remove_nodes_from(isolated)  # drop isolated species for clarity

degrees = dict(G.degree())
density = nx.density(G)
mean_degree = np.mean(list(degrees.values())) if degrees else 0.0
top3 = sorted(degrees.items(), key=lambda kv: kv[1], reverse=True)[:3]

print("--- Co-occurrence network summary (networkx) ---")
print(f"Nodes (connected species): {G.number_of_nodes()} / {n_sp} total species")
print(f"Edges (significant positive associations): {G.number_of_edges()}")
print(f"Network density: {density:.3f}")
print(f"Mean degree: {mean_degree:.2f}")
print("Top-3 hub species (highest degree):")
for name, d in top3:
    print(f"  {name}: {d}")
print()

fig, ax = plt.subplots(figsize=(8.5, 7.5), dpi=125)
pos = nx.spring_layout(G, seed=42, k=0.5)
node_sizes = [180 + 60 * degrees[n] for n in G.nodes()]
nx.draw_networkx_edges(G, pos, ax=ax, edge_color="#2E6E8E", alpha=0.6)
nx.draw_networkx_nodes(G, pos, ax=ax, node_size=node_sizes,
                        node_color="#8E5AA8", edgecolors="white", linewidths=1.0)
nx.draw_networkx_labels(G, pos, ax=ax, font_size=7)
ax.set_title("Dune Meadow Species Co-occurrence Network\n"
              "(edges = significant positive Spearman association, p < 0.05)")
ax.axis("off")
fig.tight_layout()
fig.savefig("figures/lecture_15_cooccurrence_network.png")
plt.close(fig)
print("Saved figures/lecture_15_cooccurrence_network.png\n")

# ---- 4. Simplified JSDM: per-species GLM + residual correlation ----------------
# Fit each species' abundance against a shared environmental covariate (A1 =
# soil organic matter horizon depth from dune_env.csv). After removing the
# shared environmental response, whatever correlation REMAINS among the
# Pearson residuals is the "biotic signal" -- the part of co-occurrence not
# explained by shared habitat preference. This is a hand-rolled stand-in for
# the residual covariance structure that Hmsc / boral / gllvm estimate
# jointly and more rigorously.

dune_env = pd.read_csv("data/dune_env.csv")
assert list(dune_env["site"].astype(str)) == list(site_ids)
A1 = dune_env["A1"].to_numpy()
X = sm.add_constant(A1)

resid_mat = np.empty((n_site, n_sp))
for j in range(n_sp):
    y = comm[:, j]
    model = sm.GLM(y, X, family=sm.families.Poisson())
    fit = model.fit()
    resid_mat[:, j] = fit.resid_pearson

resid_cor = np.array([
    [spearmanr(resid_mat[:, i], resid_mat[:, j])[0] if resid_mat[:, i].std() > 0
     and resid_mat[:, j].std() > 0 else 0.0
     for j in range(n_sp)]
    for i in range(n_sp)
])

lower_idx = np.tril_indices(n_sp, k=-1)
mean_abs_raw = np.nanmean(np.abs(cor_mat[lower_idx]))
mean_abs_resid = np.nanmean(np.abs(resid_cor[lower_idx]))

print("--- Simplified JSDM: species-GLM residual correlation (vs A1) ---")
print(f"Mean |raw Spearman correlation| among species:        {mean_abs_raw:.3f}")
print(f"Mean |residual correlation| after controlling for A1: {mean_abs_resid:.3f}")
if mean_abs_resid < mean_abs_raw:
    print("Residual correlation is SMALLER than raw: A1 (soil organic matter)\n"
          "explains part of the raw co-occurrence signal.")
else:
    print("Residual correlation is NOT smaller than raw here: A1 alone does not\n"
          "soak up much of the co-occurrence signal for this dataset -- either\n"
          "the true environmental driver is something else (e.g. Moisture), or\n"
          "a genuine biotic/unmeasured-covariate signal dominates.")
print("Whatever correlation remains among residuals after accounting for the\n"
      "shared environmental response is the candidate biotic-interaction\n"
      "signal -- the core logic behind JSDMs (Hmsc/boral/gllvm).\n")

print("=== Done ===")

# --- EXERCISES ---
# TODO 1: Rerun the co-occurrence analysis (Steps 1-3) on data/BCI_species.csv.
#         Subset to the ~30 most abundant species first (comm.sum(axis=0),
#         then np.argsort(...)[-30:]) to keep runtime reasonable. Compare
#         network density to the dune network.
# TODO 2: Identify the top-3 hub species in the dune co-occurrence network
#         and look up (or reason about) their functional traits/life
#         history. What ecological mechanism could explain why they have
#         so many significant positive associations?
# TODO 3: Refit the simplified JSDM (Step 4) using Moisture instead of A1
#         as the environmental covariate. Does mean residual correlation
#         drop by more or less than with A1?
# TODO 4: Repeat the null-model C-score test (Step 2) using a different
#         null-model constraint, e.g. shuffle each column independently
#         (preserving only column/species totals, not row/site totals --
#         the "fixed-equiprobable" model). Do the SES and p-value change
#         much? What does that tell you about the sensitivity of null-model
#         results to the choice of randomization algorithm?
