## ============================================================
## Lecture 15 -- Community Ecology Models (Julia)
## Ecological Modelling with R, Python, and Julia
##
## Dataset:
##   data/dune_species.csv (+ data/dune_env.csv for the JSDM covariate)
##     Jongman, ter Braak & van Tongeren -- Dutch dune meadow vegetation
##     survey, 20 sites x 30 species
##
## Lecture 4 asked whether GROUPS differ in composition (PERMANOVA/NMDS).
## Today we ask how SPECIES relate to EACH OTHER: co-occurrence, null
## models, networks, and a simplified joint species distribution model.
##
## Methods:
##   1. Pairwise Spearman correlation among species across sites
##   2. Hand-rolled null-model co-occurrence test (C-score) via a
##      fixed-fixed checkerboard-swap algorithm (row/column sums preserved),
##      the same logic as vegan::oecosimu(method="quasiswap") in R.
##      Reference: Gotelli, N.J. (2000) "Null model analysis of species
##      co-occurrence patterns." Ecology 81(9): 2606-2621.
##   3. Species co-occurrence network -- Graphs.jl
##   4. Simplified JSDM: per-species GLM (Poisson) + residual correlation
##      -- GLM.jl
##
## Assumes working directory = repository root, i.e. run as:
##   julia --project=. code/julia/lecture_15_community_models.jl
##
## NOTE: not executed in this environment (Graphs.jl/GLM.jl not installed
## in the sandbox); written carefully against the documented APIs and
## cross-checked line-for-line against the executed R and Python versions.
## ============================================================

using CSV
using DataFrames
using Statistics
using StatsBase: corspearman
using Random
using GLM
using Graphs
using GraphPlot                 # gplot() -> Compose.jl drawing
using Compose: draw, PNG, cm
using Colors: RGBA
using SpecialFunctions: beta_inc

mkpath("figures")

println("=== Lecture 15: Community Ecology Models (Julia) ===\n")

## ------------------------------------------------------------
## 0. Load data
## ------------------------------------------------------------

dune = CSV.read("data/dune_species.csv", DataFrame)
site_ids = string.(dune.site)
sp_names = names(dune)[names(dune) .!= "site"]
comm = Matrix{Float64}(dune[:, sp_names])
n_site, n_sp = size(comm)
println("Community matrix: $n_site sites x $n_sp species\n")

## ------------------------------------------------------------
## 1. Pairwise Spearman correlation among species across sites
##    Each species' abundance vector (length = 20 sites) is correlated
##    against every other species' vector. This is a purely descriptive,
##    raw-data association -- it does NOT yet account for the fact that
##    species which are individually common will co-occur more often by
##    chance alone. Step 2 fixes that.
## ------------------------------------------------------------

cor_mat = corspearman(comm)   # n_sp x n_sp Spearman correlation matrix

# corspearman() gives no p-values, so approximate them with the standard
# large-n Spearman t-approximation: t = r * sqrt((n-2)/(1-r^2)), df = n-2.
function spearman_pvalue(r::Float64, n::Int)
    if abs(r) >= 1.0
        return 0.0
    end
    t = r * sqrt((n - 2) / (1 - r^2))
    # two-sided p-value from Student's t via the regularized incomplete beta
    # (avoids adding Distributions.jl as a hard dependency for one call);
    # in practice use Distributions.jl: 2*ccdf(TDist(n-2), abs(t))
    df = n - 2
    x = df / (df + t^2)
    p = beta_inc(df / 2, 0.5, x)[1]
    return p
end

p_mat = fill(1.0, n_sp, n_sp)
for i in 1:(n_sp - 1), j in (i + 1):n_sp
    r = cor_mat[i, j]
    p = spearman_pvalue(r, n_site)
    p_mat[i, j] = p_mat[j, i] = p
end

n_pairs = div(n_sp * (n_sp - 1), 2)
sig_pos = falses(n_sp, n_sp)
for i in 1:n_sp, j in 1:n_sp
    if i != j && p_mat[i, j] < 0.05 && cor_mat[i, j] > 0
        sig_pos[i, j] = true
    end
end
n_sig = div(sum(sig_pos), 2)

println("--- Pairwise Spearman correlations among species ---")
println("Total species pairs tested: $n_pairs")
println("Significant positive pairs (uncorrected p < 0.05): $n_sig ",
        "($(round(100 * n_sig / n_pairs, digits = 1))%)")
println("Expected false positives under the null at alpha=0.05: ~",
        round(0.05 * n_pairs, digits = 1))
println("CAVEAT: 30 species means 435 tests -- uncorrected p<0.05 gives ~22")
println("false positives by chance. Fine for teaching; a real analysis should")
println("use FDR correction or, better, the null-model test below.\n")

## ------------------------------------------------------------
## 2. Hand-rolled null-model co-occurrence test (C-score)
##    Gotelli (2000, Ecology) formalized null-model testing of species
##    co-occurrence: compare the OBSERVED checkerboard (C-)score of a
##    presence-absence matrix to a null distribution generated by
##    randomizing the matrix while preserving row and column sums (the
##    "fixed-fixed" algorithm, equivalent to vegan's "quasiswap"). We swap
##    checkerboard submatrices [[1,0],[0,1]] <-> [[0,1],[1,0]], which
##    preserves every row sum and column sum exactly.
## ------------------------------------------------------------

pa = Int.(comm .> 0)

function cscore(pa_mat::Matrix{Int})
    n = size(pa_mat, 2)
    row_totals = vec(sum(pa_mat, dims = 1))  # occurrences per species
    total = 0.0
    count = 0
    for i in 1:(n - 1), j in (i + 1):n
        shared = sum((pa_mat[:, i] .== 1) .& (pa_mat[:, j] .== 1))
        ri, rj = row_totals[i], row_totals[j]
        total += (ri - shared) * (rj - shared)
        count += 1
    end
    return total / count
end

function swap_null!(m::Matrix{Int}, n_swaps::Int, rng::AbstractRNG)
    n_site_, n_sp_ = size(m)
    tries = 0
    swaps_done = 0
    max_tries = n_swaps * 50
    while swaps_done < n_swaps && tries < max_tries
        tries += 1
        r1, r2 = rand(rng, 1:n_site_, 2)
        r1 == r2 && continue
        c1, c2 = rand(rng, 1:n_sp_, 2)
        c1 == c2 && continue
        block = m[[r1, r2], [c1, c2]]
        if block == [1 0; 0 1]
            m[r1, c1], m[r1, c2] = 0, 1
            m[r2, c1], m[r2, c2] = 1, 0
            swaps_done += 1
        elseif block == [0 1; 1 0]
            m[r1, c1], m[r1, c2] = 1, 0
            m[r2, c1], m[r2, c2] = 0, 1
            swaps_done += 1
        end
    end
    return m
end

Random.seed!(42)
obs_c = cscore(pa)
n_null = 999
null_c = Vector{Float64}(undef, n_null)
mat = copy(pa)
for k in 1:n_null
    swap_null!(mat, 200, Random.default_rng())
    null_c[k] = cscore(mat)
end

z_score = (obs_c - mean(null_c)) / std(null_c)
p_null = (count(>=(obs_c), null_c) + 1) / (n_null + 1)

println("--- Null-model co-occurrence test (hand-rolled C-score, fixed-fixed swap) ---")
println("Observed C-score: ", round(obs_c, digits = 3))
println("Null mean C-score: ", round(mean(null_c), digits = 3),
        " (SD ", round(std(null_c), digits = 3), ")")
println("SES (z) = ", round(z_score, digits = 2),
        ", p = ", round(p_null, digits = 3), " ($n_null null replicates)")
println("Interpretation: SES > 0 with p < 0.05 => species segregation")
println("(checkerboard structure) beyond what random co-occurrence predicts,")
println("consistent with the R and Python results.\n")

## ------------------------------------------------------------
## 3. Species co-occurrence network -- Graphs.jl
##    Nodes = species; edges = significant POSITIVE pairwise association
##    (from Step 1).
## ------------------------------------------------------------

g = SimpleGraph(n_sp)
for i in 1:(n_sp - 1), j in (i + 1):n_sp
    if sig_pos[i, j]
        add_edge!(g, i, j)
    end
end

deg = degree(g)
keep = findall(deg .> 0)   # drop isolated species for clarity
g_conn, vmap = induced_subgraph(g, keep)
deg_conn = degree(g_conn)
labels_conn = sp_names[keep]

dens = density(g_conn)
mean_deg = mean(deg_conn)
order = sortperm(deg_conn, rev = true)
top3_idx = order[1:min(3, length(order))]

println("--- Co-occurrence network summary (Graphs.jl) ---")
println("Nodes (connected species): $(nv(g_conn)) / $n_sp total species")
println("Edges (significant positive associations): $(ne(g_conn))")
println("Network density: ", round(dens, digits = 3))
println("Mean degree: ", round(mean_deg, digits = 2))
println("Top-3 hub species (highest degree):")
for idx in top3_idx
    println("  ", labels_conn[idx], ": ", deg_conn[idx])
end
println()

# Network plot -> figures/lecture_15_cooccurrence_network.png
node_sizes = 4 .+ 1.5 .* deg_conn
draw(PNG("figures/lecture_15_cooccurrence_network.png", 15cm, 13cm),
     gplot(g_conn,
           nodelabel = labels_conn,
           nodesize = node_sizes,
           nodefillc = RGBA(0.56, 0.35, 0.66, 0.9),
           edgestrokec = RGBA(0.18, 0.43, 0.56, 0.6),
           nodelabelsize = 3.0))
println("Saved figures/lecture_15_cooccurrence_network.png\n")

## ------------------------------------------------------------
## 4. Simplified JSDM: per-species GLM + residual correlation
##    Fit each species' abundance against a shared environmental
##    covariate (A1 = soil organic matter horizon depth from dune_env.csv).
##    After removing the shared environmental response, whatever
##    correlation REMAINS among the Pearson residuals is the "biotic
##    signal" -- the part of co-occurrence not explained by shared habitat
##    preference. This is a hand-rolled stand-in for the residual
##    covariance structure that Hmsc / boral / gllvm estimate jointly and
##    more rigorously.
## ------------------------------------------------------------

dune_env = CSV.read("data/dune_env.csv", DataFrame)
@assert string.(dune_env.site) == site_ids
A1 = Float64.(dune_env.A1)

resid_mat = Matrix{Float64}(undef, n_site, n_sp)
for j in 1:n_sp
    y = comm[:, j]
    df_j = DataFrame(y = y, A1 = A1)
    fit_j = glm(@formula(y ~ A1), df_j, Poisson(), LogLink())
    mu = predict(fit_j)
    resid_mat[:, j] = (y .- mu) ./ sqrt.(mu)   # Pearson residuals
end

resid_cor = corspearman(resid_mat)

lower_idx = [(i, j) for i in 2:n_sp for j in 1:(i - 1)]
mean_abs_raw = mean(abs(cor_mat[i, j]) for (i, j) in lower_idx)
mean_abs_resid = mean(abs(resid_cor[i, j]) for (i, j) in lower_idx)

println("--- Simplified JSDM: species-GLM residual correlation (vs A1) ---")
println("Mean |raw Spearman correlation| among species:        ",
        round(mean_abs_raw, digits = 3))
println("Mean |residual correlation| after controlling for A1: ",
        round(mean_abs_resid, digits = 3))
if mean_abs_resid < mean_abs_raw
    println("Residual correlation is SMALLER than raw: A1 (soil organic matter)")
    println("explains part of the raw co-occurrence signal.")
else
    println("Residual correlation is NOT smaller than raw here: A1 alone does not")
    println("soak up much of the co-occurrence signal for this dataset -- either")
    println("the true environmental driver is something else (e.g. Moisture), or")
    println("a genuine biotic/unmeasured-covariate signal dominates.")
end
println("Whatever correlation remains among residuals after accounting for the")
println("shared environmental response is the candidate biotic-interaction")
println("signal -- the core logic behind JSDMs (Hmsc/boral/gllvm).\n")

println("=== Done ===")

## --- EXERCISES ---
## TODO 1: Rerun the co-occurrence analysis (Steps 1-3) on data/BCI_species.csv.
##         Subset to the ~30 most abundant species first (sum along columns,
##         then partialsortperm(..., 1:30, rev=true)) to keep runtime
##         reasonable. Compare network density to the dune network.
## TODO 2: Identify the top-3 hub species in the dune co-occurrence network
##         and look up (or reason about) their functional traits/life
##         history. What ecological mechanism could explain why they have
##         so many significant positive associations?
## TODO 3: Refit the simplified JSDM (Step 4) using Moisture instead of A1
##         as the environmental covariate. Does mean residual correlation
##         drop by more or less than with A1?
## TODO 4: Repeat the null-model C-score test (Step 2) using a different
##         null-model constraint, e.g. shuffle each column independently
##         (preserving only column/species totals, not row/site totals --
##         the "fixed-equiprobable" model). Do the SES and p-value change
##         much? What does that tell you about the sensitivity of null-model
##         results to the choice of randomization algorithm?
